### ISSUE TITLE
Communication error:  Server closed communication device

### ISSUE THREAD

**Issue by tjlee** [daimor/docker-intersystems#1]
I'm trying to run tests against InterSystem Cache in Docker container. 
When I run container locally - everything is fine. 
When I run container in remote TeamCity agent - I'm getting `Server closed communication device` error. 

Environment: 

Database: Cache (ver. Cache Objects Version 2017.2.2.865 Cache xDBC Server 8.01) 
Identifier case sensitivity: mixed (plain), mixed (delimited) 
Driver (JDBC4.2): InterSystems Cache JDBC (ver. 2016.1.1.108) 

jdbc:Cache://localhost:1972/Samples/::false?username=_SYSTEM&password=SYS

docker-compose.yml
```yml
version: '2.1'
services:
    intersystemscache:
      container_name: intersystemscache
      image: daimor/intersystems-cache:2017.2
      ports:
        - "1972:1972"
      healthcheck:
        test: grep -r "Starting Super Server on port" /usr/cachesys/mgr/cconsole.log
        interval: 3m
        timeout: 10s
        retries: 5
```
```java
java.sql.SQLException: Communication error: Communication error:  Server closed communication device
	at com.intersys.jdbc.InStream.readBuffer(InStream.java:142)
	at com.intersys.jdbc.InStream.checkHeader(InStream.java:169)
	at com.intersys.jdbc.InStream.readMessage(InStream.java:265)
	at com.intersys.jdbc.InStream.readMessage(InStream.java:204)
	at com.intersys.jdbc.CacheConnection.connect(CacheConnection.java:1094)
	at com.intersys.jdbc.CacheConnection.<init>(CacheConnection.java:418)
	at com.intersys.jdbc.CacheDriver.connect(CacheDriver.java:244)
	at com.intellij.database.remote.jdbc.impl.RemoteDriverImpl.connect(RemoteDriverImpl.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Do I need to specify additional connection options for KeepAlive or any Timeouts?

**Comment by daimor** [comment]
I don't see that you use any license key, this image does not contain any license, so, you should use own key. And server without a key has a limitation in connections. Try to mount `cache.key` to `/usr/cachesys/mgr/cache.key` for the latest build or `/opt/cache/mgr/cache.key` for any previous one.

**Comment by tjlee** [comment]
Is there any express or developer edition for testing purposes?

**Comment by daimor** [comment]
Version without license can work in some way, but not so good, it is limited as 1 license unit.
Better to ask for a temporary license, I'm sure they will do it for you.

**Comment by daimor** [comment]
Could you contact me directly via email? So, maybe I can help you, not with the license, but to see what are your trying to achieve. I have not tried TeamCity yet, and don't understand how you use Caché in your case.
